### ISSUE TITLE
Issue in executing optimize_hyperparams.py

### ISSUE THREAD

**Issue by Bugjub** [amineHorseman/facial-expression-recognition-using-cnn#13]
Hi,
Can anybody guide me as to why am I getting this error while I try to run the optimize_hyperparams.py : line 7, import pprint(
SyntaxError: invalid syntax

Thanks

**Comment by amineHorseman** [comment]
Hi, 
I just pushed a commit correcting the error 
Thank you for helping finding bugs

**Comment by Bugjub** [comment]
@amineHorseman : All print commands in the optimize_hyperparams.py have syntax errors. You may want to re-check the complete file for errors. For example:
Line 47 print( "#################################"
Line 48 print( " Evaluation {} of {}".format(current_eval, max_evals)
Line 49 print( "#################################"
Line 60 print( "#################################"
Line 61 print( "Exception during training: {}".format(str(e))
Line 62 print( "Saving train history in train_history.npy"
Line 78 print( "#################################"
Line 79 print( " Best parameters found"
Line 80 print( "#################################"
Line 81 pprint(.pprint((best_trial)
Line 82 print( "#################################"
Thanks
