### ISSUE TITLE
about the accuracy

### ISSUE THREAD

**Issue by dagongji10** [amineHorseman/facial-expression-recognition-using-cnn#14]
Hi, I have some problems in optimizer param. I run the optimize_hyperparams.py with max_evals=20, but still cannot get the acc of 75.1%. In fact, my results always under 70%. 
Is the value of max_evals setting too small? I use 5 emotions(angry, happy, sad, suprise, neytral). Could you help me?

**Comment by amineHorseman** [comment]
Well, that's pretty strange since I got everytime a score over 70% for the model B, did you change some parameter? can you print your parameters.py file?

**Comment by dagongji10** [comment]
> Well, that's pretty strange since I got everytime a score over 70% for the model B, did you change some parameter? can you print your parameters.py file?

In fact， I changed the database and network. The labels of Fer2013 are not exactly and size of image is too small, so I use RAF-DB to replace Fer2013.
Finally, I can get 83~84% acc using 7 emotion.
