### ISSUE TITLE
Landmarks and hog feature

### ISSUE THREAD

**Issue by NomiMalik0207** [amineHorseman/facial-expression-recognition-using-cnn#16]
great work man
i want to know about how you are feeding landmarks and hog features to your network?
either you are putting in the form of label of same like image?

**Comment by amineHorseman** [comment]
Thank you @NomiMalik0207 
For landmarks it's a 2 by 67 matrix corresponding to the (x, y) coordinates of 67 points of interests
For the hog features I feed the vector directly to the cnn then I merge it with the landmarks and the dense layer after processing the images as shown in the diagram
