### ISSUE TITLE
hello，some question about the acc of  classification

### ISSUE THREAD

**Issue by ssxxx1a** [amineHorseman/facial-expression-recognition-using-cnn#21]
I tested your model, but the recognition rate was only 41%。

**Comment by amineHorseman** [comment]
41% is rather low as accuracy, it should be bigger than the svm accuracy

Can you explain in details what did you try, how much data, and which parameters?

**Comment by ssxxx1a** [comment]
I've trained the model according to your tutorial,  would you please provide pre-trained model?

**Comment by amineHorseman** [comment]
I didn't keep the pre-trained model, but you should modify the following two lines in `convert_fer2013_to_images_and_landmarks.py` (lines 23, 24):

```
SELECTED_LABELS = []
IMAGES_PER_LABEL = 500
```

The first one to choose which facial expressions to use, during my experiments I used 5 emotions:

```
SELECTED_LABELS = [0,3,4,5,6]
```

The second one is the number of images to use for each emotion, I put 500 only to test quickly during the debugging, but in the final experiment you should put a big number to use all the data available: 

```
IMAGES_PER_LABEL = 999999
```

Don't forget to set the right number of emotions in the `parameter.py` file, line 7:

```
output_size = 5
```
