### ISSUE TITLE
error while using predict.py

### ISSUE THREAD

**Issue by 0xinit** [amineHorseman/facial-expression-recognition-using-cnn#27]
hi,

I'm constantly getting this error whenever I try to run predict.py. I am not sure what is wrong. Is it because of some package update? 

Use standard file APIs to check for files with this prefix.
/home/gaurav/anaconda3/envs/openface/lib/python2.7/site-packages/skimage/feature/_hog.py:150: skimage_deprecation: Default value of `block_norm`==`L1` is deprecated and will be changed to `L2-Hys` in v0.15. To supress this message specify explicitly the normalization method.
  skimage_deprecation)
/home/gaurav/anaconda3/envs/openface/lib/python2.7/site-packages/skimage/feature/_hog.py:248: skimage_deprecation: Argument `visualise` is deprecated and will be changed to `visualize` in v0.16
  'be changed to `visualize` in v0.16', skimage_deprecation)
Traceback (most recent call last):
  File "predict.py", line 93, in <module>
    emotion, confidence = predict(image, model, shape_predictor)
  File "predict.py", line 57, in predict
    hog_features = sliding_hog_windows(image)
  File "predict.py", line 47, in sliding_hog_windows
    cells_per_block=(1, 1), visualise=False))
  File "/home/gaurav/anaconda3/envs/openface/lib/python2.7/site-packages/skimage/feature/_hog.py", line 211, in hog
    g_row, g_col = _hog_channel_gradient(image)
  File "/home/gaurav/anaconda3/envs/openface/lib/python2.7/site-packages/skimage/feature/_hog.py", line 41, in _hog_channel_gradient
    g_col[:, 0] = 0
IndexError: index 0 is out of bounds for axis 1 with size 0

**Comment by kaavyaastalin** [comment]
I think, you are using python 2.7 version, Try to update the python version and try to run the code.

check it out below link to upgrade the python version:

https://stackoverflow.com/questions/41535881/how-do-i-upgrade-to-python-3-6-with-conda

If you are using anaconda spyder to run the rode, try to use the virtual environment. Meantime update all packages in the virtual environment.
: )

**Comment by 0xinit** [comment]
Yes, I didn't realize that python3 was required. There were some other errors, but I got them done. Thanks a lot.
