### ISSUE TITLE
Unexpected error occured

### ISSUE THREAD

**Issue by omkarhp** [amineHorseman/facial-expression-recognition-using-cnn#4]
![capture](https://user-images.githubusercontent.com/43632951/46127331-03b17800-c24e-11e8-808c-557df4ad4a0f.PNG)
  while running predict.py in command prompt im getting this unexpected error message that "Python has stopped working"
please help.

**Comment by amineHorseman** [comment]
Can you provide more information?
Python version? opencv version? do you use an anaconda environment? is there any other messages in the command console?

**Comment by amineHorseman** [comment]
Closing the issue for inactivity. Feel free to reopen it if needed.
