### ISSUE TITLE
unable to open shape predictor.

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [amineHorseman/facial-expression-recognition-using-cnn#6]
File "G:/Asad/Projects/facial-expression-recognition-using-cnn-master/facial-expression-recognition-using-cnn-master/convert_fer2013_to_images_and_landmarks.py", line 61, in <module>
    predictor = dlib.shape_predictor('shape_predictor_68_face_landmarks.dat')

RuntimeError: Unable to open shape_predictor_68_face_landmarks.dat

**Comment by amineHorseman** [comment]
Can you give more details about this issue?

Which version of python and opencv and dlib do you use?

Please make sure the file "shape_predictor_68_face_landmarks.dat" exists in the repository folder (in your case these folder: "`G:/Asad/Projects/facial-expression-recognition-using-cnn-master/facial-expression-recognition-using-cnn-master/`")

**Comment by MuhammadAsadJaved** [comment]
The problem have been resolved. Thank you very much. @amineHorseman
