### ISSUE TITLE
Issue in train.py

### ISSUE THREAD

**Issue by gudiausha** [amineHorseman/facial-expression-recognition-using-cnn#7]
@amineHorseman sir, When i run  python train.py --train=yes in cmd, its throwing an error in line 22 in train.py, which leads to line 31 in data_loader.py and i get an error saying "all the input array dimensions except for the concatenation  axis must match exactly." I have not changed anything in the code. Thank you..

**Comment by amineHorseman** [comment]
Hello @gudiausha 
Can you make a screenshot of copy the entire text of the cmd window?

**Comment by amineHorseman** [comment]
Closing the issue for inactivity. Feel free to reopen it if needed.
