### ISSUE TITLE
Issue with train.py

### ISSUE THREAD

**Issue by sandeepalur** [amineHorseman/facial-expression-recognition-using-cnn#8]
@amineHorseman Quick observation. Noticed that when we run "convert_fer2013_to_images_and_landmarks.py" for expressions less than 7, and when we run train.py, we get an exception which says "axis 1 out of bounds for array of dimension 1". 
![error](https://user-images.githubusercontent.com/18388366/48081192-7b8f9c80-e215-11e8-823f-6074798b6ac3.JPG)

**Comment by sandeepalur** [comment]
Figured out the above issue, and it was due to the fact that data for validation was empty. In convert_fer2013_to_images_and_landmarks.py file, line 169, the counter for 'nb_images_per_label' reaches IMAGES_PER_LABEL for training itself and hence when extracting Validation labels, the control never goes into 'If Loop'. Fixed this locally to increment the IMAGES_PER_LABEL counter to accommodate the # of labels we need for Training and Testing. Will create a pull request soon with few additional minor changes to accommodate when training for less than 7 expression. Otherwise, @amineHorseman, this is great piece of work from you.

**Comment by amineHorseman** [comment]
Thank you @sandeepalur 
Sorry for late reply
Yes feel free to send a pull request when you finish your modifications
