### ISSUE TITLE
Run model on test image using predict.py

### ISSUE THREAD

**Issue by ajaysh2193** [amineHorseman/facial-expression-recognition-using-cnn#9]
Hi, I am facing an issue when I am running python predict.py --image pic.jpg to test the prediction on a random image. I downloaded the angry face image randomly from internet and try to check the model predicition. But I am getting error as below (please check screenshot).
 Your help would be much appreciated!
![error](https://user-images.githubusercontent.com/24571705/48946890-311c5880-ef55-11e8-9f85-4ad403cdb855.png)

Regards,
Ajay Sharma

**Comment by amineHorseman** [comment]
Hi @ajaysh2193 

It seems the image you tried is bigger than what the cnn expected
Please add the following line in the file `predict.py` just before line 67:

> image = cv2.resize(image, (NETWORK.input_size, NETWORK.input_size))
